/**
 * Reads markdown files under `public/` and emits a generated TS module with
 * a slug → contents map. The docs page imports from this module so we get
 * the content as plain strings at runtime, with no fs / fetch / ASSETS
 * binding involved.
 *
 * Invoked from `next.config.ts` so every build path (next dev, next build,
 * opennextjs-cloudflare build, ...) regenerates before bundling.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const DOC_FILES: Array<{ slug: string; filePath: string }> = [
  { slug: 'quick-start', filePath: 'docs/quick-start.md' },
  { slug: 'sdk-reference', filePath: 'docs/sdk-reference.md' },
  { slug: 'opentelemetry', filePath: 'docs/opentelemetry.md' },
  { slug: 'agents', filePath: 'agents.md' },
  { slug: 'collector', filePath: 'docs/collector.md' },
  { slug: 'mcp', filePath: 'docs/mcp.md' },
];

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const WEB_DIR = path.resolve(SCRIPT_DIR, '..');

function escapeForTemplateLiteral(content: string): string {
  return content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

export function generateDocsContent(): void {
  const publicDir = path.join(WEB_DIR, 'public');
  const outputFile = path.join(WEB_DIR, 'src/generated/docs-content.ts');

  const entries: string[] = [];
  for (const { slug, filePath } of DOC_FILES) {
    const fullPath = path.join(publicDir, filePath);
    const content = readFileSync(fullPath, 'utf8');
    entries.push(`  '${slug}': \`${escapeForTemplateLiteral(content)}\`,`);
  }

  const output = `// Generated by scripts/generate-docs-content.ts — do not edit.
// Refreshed automatically by next.config.ts on every build.

export const DOCS_CONTENT: Record<string, string> = {
${entries.join('\n')}
};
`;

  mkdirSync(path.dirname(outputFile), { recursive: true });
  writeFileSync(outputFile, output, 'utf8');
}

const invokedDirectly =
  import.meta.url === `file://${process.argv[1]}` || process.argv[1]?.endsWith(import.meta.url);
if (invokedDirectly) {
  generateDocsContent();
  console.log(`docs:generate → wrote ${DOC_FILES.length} docs`);
}
