/**
 * Reads every `skills/<name>/SKILL.md` in the repo and emits a generated TS
 * module holding the skill contents plus a SHA-256 digest of the exact bytes.
 *
 * The digest published in the discovery index has to match the bytes we serve,
 * so the content and the hash come from one read of one file. Invoked from
 * `next.config.ts` so every build path regenerates before bundling.
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const WEB_DIR = path.resolve(SCRIPT_DIR, '..');
const SKILLS_DIR = path.resolve(WEB_DIR, '../../skills');

// RFC: 1-64 chars, lowercase alphanumeric and hyphens, no leading, trailing,
// or consecutive hyphens.
const NAME_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const MAX_NAME_LENGTH = 64;
const MAX_DESCRIPTION_LENGTH = 1024;

interface SkillFrontmatter {
  name: string;
  description: string;
}

interface GeneratedSkill extends SkillFrontmatter {
  content: string;
  digest: string;
}

function readFrontmatterField(frontmatter: string, field: string, source: string): string {
  const lines = frontmatter.split('\n');
  const start = lines.findIndex((line) => line.startsWith(`${field}:`));
  if (start === -1) {
    throw new Error(`${source}: frontmatter is missing a "${field}" field`);
  }

  const first = lines[start].slice(field.length + 1).trim();
  if (first.startsWith('|') || first.startsWith('>')) {
    throw new Error(`${source}: "${field}" is a YAML block scalar; use a plain or quoted scalar`);
  }

  // A plain scalar folds across more-indented continuation lines. Join them
  // instead of reading the first line, which would publish a truncated value.
  const parts = [first];
  for (let i = start + 1; i < lines.length; i += 1) {
    const line = lines[i];
    if (!/^\s/.test(line) || line.trim() === '') break;
    parts.push(line.trim());
  }

  const value = parts
    .join(' ')
    .trim()
    .replace(/^(['"])([\s\S]*)\1$/, '$2');
  if (!value) {
    throw new Error(`${source}: frontmatter field "${field}" is empty`);
  }
  return value;
}

export function parseSkillFrontmatter(
  content: string,
  expectedName: string,
  source: string,
): SkillFrontmatter {
  const frontmatter = /^---\n([\s\S]*?)\n---\n/.exec(content)?.[1];
  if (!frontmatter) {
    throw new Error(`${source}: missing YAML frontmatter`);
  }

  const name = readFrontmatterField(frontmatter, 'name', source);
  const description = readFrontmatterField(frontmatter, 'description', source);

  if (name !== expectedName) {
    throw new Error(
      `${source}: frontmatter name "${name}" does not match directory "${expectedName}"`,
    );
  }
  if (name.length > MAX_NAME_LENGTH || !NAME_PATTERN.test(name)) {
    throw new Error(`${source}: name "${name}" is not a valid discovery skill name`);
  }
  if (description.length > MAX_DESCRIPTION_LENGTH) {
    throw new Error(
      `${source}: description is ${description.length} characters, over the ${MAX_DESCRIPTION_LENGTH} limit`,
    );
  }

  return { name, description };
}

function readSkill(dirName: string): GeneratedSkill {
  const source = path.join(SKILLS_DIR, dirName, 'SKILL.md');
  const raw = readFileSync(source);
  const content = raw.toString('utf8');

  // The served response re-encodes this string as UTF-8. If that round trip is
  // lossy the published digest would describe bytes nobody receives.
  if (!Buffer.from(content, 'utf8').equals(raw)) {
    throw new Error(`${source}: not valid UTF-8, so the digest cannot describe the served bytes`);
  }

  return {
    ...parseSkillFrontmatter(content, dirName, source),
    content,
    digest: `sha256:${createHash('sha256').update(raw).digest('hex')}`,
  };
}

export function generateAgentSkills(): number {
  const dirNames = readdirSync(SKILLS_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();

  const skills = dirNames.map(readSkill);
  const outputFile = path.join(WEB_DIR, 'src/generated/agent-skills.ts');

  const output = `// Generated by scripts/generate-agent-skills.ts — do not edit.
// Refreshed automatically by next.config.ts on every build.

export interface GeneratedSkill {
  name: string;
  description: string;
  content: string;
  digest: string;
}

export const AGENT_SKILLS: GeneratedSkill[] = ${JSON.stringify(skills, null, 2)};
`;

  mkdirSync(path.dirname(outputFile), { recursive: true });
  writeFileSync(outputFile, output, 'utf8');
  return skills.length;
}

const invokedDirectly =
  import.meta.url === `file://${process.argv[1]}` || process.argv[1]?.endsWith(import.meta.url);
if (invokedDirectly) {
  console.log(`skills:generate → wrote ${generateAgentSkills()} skills`);
}
