name = "observe-api"
main = "src/index.ts"
compatibility_date = "2024-11-27"

[observability]
enabled = true

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "observe-storage-dev"

[env.staging]
name = "observe-api-staging"

[[env.staging.r2_buckets]]
binding = "STORAGE"
bucket_name = "observe-storage-staging"

[env.production]
name = "observe-api-production"

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "observe-storage-prod"
