name = "trace-flow-api-dev"
main = "src/index.ts"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat", "no_nodejs_compat_v2"]
upload_source_maps = true

[observability]
enabled = true

[version_metadata]
binding = "CF_VERSION_METADATA"

[vars]
AUTH0_DOMAIN = "auth0.zaks.io"
AUTH0_CLIENT_ID = "iyvisDUHrcsFGZYWdxZrX7LH8rtnT50W"
SENTRY_ENVIRONMENT = "development"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "trace-flow-storage-dev"

[[kv_namespaces]]
binding = "API_KEYS"
id = "30c9a31ff3af4b408b4d64b8ecfa98a5"

[env.production]
name = "trace-flow-api"
workers_dev = false

[env.production.vars]
AUTH0_DOMAIN = "auth0.zaks.io"
AUTH0_CLIENT_ID = "asEG3J6UWZOeKWclu2WxONmoIhTsCfdp"
SENTRY_ENVIRONMENT = "production"

[[env.production.routes]]
pattern = "api.trace-flow.dev/*"
zone_name = "trace-flow.dev"

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "trace-flow-storage-prod"

[[env.production.kv_namespaces]]
binding = "API_KEYS"
id = "f004c21e2b8c4754af5947c08069bd00"

[env.preview]
name = "trace-flow-api-preview"

[env.preview.vars]
AUTH0_DOMAIN = "auth0.zaks.io"
AUTH0_CLIENT_ID = "iyvisDUHrcsFGZYWdxZrX7LH8rtnT50W"
SENTRY_ENVIRONMENT = "preview"

[[env.preview.r2_buckets]]
binding = "STORAGE"
bucket_name = "trace-flow-storage-dev"

[[env.preview.kv_namespaces]]
binding = "API_KEYS"
id = "30c9a31ff3af4b408b4d64b8ecfa98a5"
