name = "observe-api"
main = "src/index.ts"
compatibility_date = "2024-11-27"

[observability]
enabled = true

[vars]
AUTH0_DOMAIN = "auth0.zaks.io"
AUTH0_CLIENT_ID = "iyvisDUHrcsFGZYWdxZrX7LH8rtnT50W"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "observe-storage-dev"

[env.production]
name = "observe-api"
workers_dev = true

[env.production.vars]
AUTH0_DOMAIN = "auth0.zaks.io"
AUTH0_CLIENT_ID = "asEG3J6UWZOeKWclu2WxONmoIhTsCfdp"

[[env.production.routes]]
pattern = "api.trace-flow.dev/*"
zone_name = "trace-flow.dev"

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "observe-storage-prod"

[env.preview]
name = "observe-api-preview"

[env.preview.vars]
AUTH0_DOMAIN = "auth0.zaks.io"
AUTH0_CLIENT_ID = "iyvisDUHrcsFGZYWdxZrX7LH8rtnT50W"

[[env.preview.r2_buckets]]
binding = "STORAGE"
bucket_name = "observe-storage-dev"
