import type { ModelPricing } from '@trace-flow/pricing';
import type { StartPiRunRequest } from './request';

const RUNNER_PATH = '/workspace/traceflow-pi-runner.mjs';
const REQUEST_PATH = (runId: string) => `/workspace/runs/${runId}/request.json`;
const CONTROL_PATH = (runId: string) => `/workspace/runs/${runId}/controls.jsonl`;

export function getPiRunnerPaths(runId: string) {
  return {
    runnerPath: RUNNER_PATH,
    requestPath: REQUEST_PATH(runId),
    controlPath: CONTROL_PATH(runId),
    runDir: `/workspace/runs/${runId}`,
  };
}

export function buildPiRunRequest(request: StartPiRunRequest) {
  return JSON.stringify(
    {
      runId: request.runId,
      prompt: request.prompt,
      pageContextReferences: request.pageContextReferences,
      maxRuntimeMs: request.maxRuntimeMs,
      model: request.model,
      thinkingLevel: request.thinkingLevel,
      toolDefinitions: request.toolDefinitions,
      resume: request.resume ?? false,
    },
    null,
    2,
  );
}

export function buildPiWorkspaceManifest() {
  return [
    '# Trace Flow Analyst Pi Runner',
    '',
    'This workspace is generated by Trace Flow for one sandboxed Analyst run.',
    '',
    'Trust boundary:',
    '- The workspace itself is intentionally trusted for Pi startup.',
    '- Ambient Pi discovery is disabled for skills, prompt templates, themes, context files, and project-local extensions.',
    '- The only loaded extension is the generated Trace Flow context guard. It rejects (does not truncate) oversized tool results and provider context, so retry rejected calls with a more focused query.',
    '- All Trace Flow data access goes through the typed Python client at /workspace/traceflow_client.py. There is no data tool that returns rows into the conversation; you fetch and reduce data in code so your context stays small and runs stay cheap.',
    '- `from traceflow_client import tf` exposes one DataFrame-returning method per approved tool (plus *_raw JSON variants). It fetches over a sandbox-local Trace Flow Data API, pages, validates, and caches per run.',
    '- The data fetched by the client stays in the sandbox process. Only the summaries you compute and print enter the model context.',
    '- Convex verifies the run token, creator, org, disabled-user state, and current permissions on every data call.',
    '- The sandbox does not receive Tinybird admin tokens, Convex admin credentials, OpenRouter keys, or user session tokens.',
    '',
    'Expected inputs:',
    '- /workspace/traceflow_client.py',
    '- /workspace/runs/<runId>/request.json',
    '- /workspace/runs/<runId>/controls.jsonl',
    '- /workspace/runs/<runId>/traceflow-context-guard.ts',
    '- /workspace/.pi/agent/models.json',
    '',
  ].join('\n');
}

/** Pi prices a run in-sandbox from these rates, in US dollars per million tokens. */
export interface PiModelCost {
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite: number;
}

/**
 * Converts a MODEL_PRICING record into Pi's models.json `cost` block. KV stores microdollars per
 * million tokens; Pi prices in US dollars per million, hence the / 1e6. Unset cache rates fall back
 * to the prompt rate (matching the consumers' calculateCost). Pure: no I/O, so it is unit-testable.
 */
export function pricingToPiCost(pricing: ModelPricing): PiModelCost {
  const perMillion = (microdollars: number | undefined, fallback: number): number =>
    (microdollars ?? fallback) / 1_000_000;
  return {
    input: perMillion(pricing.promptCostPerMillion, 0),
    output: perMillion(pricing.completionCostPerMillion, 0),
    cacheRead: perMillion(pricing.cacheReadCostPerMillion, pricing.promptCostPerMillion),
    cacheWrite: perMillion(pricing.cacheWriteCostPerMillion, pricing.promptCostPerMillion),
  };
}

export function buildPiModelsJson(model: string, aiProxyBaseUrl: string, cost: PiModelCost) {
  return JSON.stringify(
    {
      providers: {
        'traceflow-openrouter': {
          name: 'Trace Flow OpenRouter Proxy',
          baseUrl: aiProxyBaseUrl,
          api: 'openai-completions',
          authHeader: true,
          headers: {
            'HTTP-Referer': 'https://traceflow.dev',
            'X-Title': 'Trace Flow Analyst Pi',
          },
          models: [
            {
              id: model,
              name: model,
              reasoning: true,
              input: ['text'],
              contextWindow: 128000,
              maxTokens: 4096,
              cost,
              compat: {
                cacheControlFormat: 'anthropic',
              },
            },
          ],
        },
      },
    },
    null,
    2,
  );
}
