export const PI_CONTEXT_GUARD_SOURCE = String.raw`function buildTraceflowContextGuardExtension() {
  return [
    'function requiredGuardEnv(name) {',
    '  const value = process.env[name];',
    "  if (!value) throw new Error('Trace Flow context guard missing required env: ' + name);",
    '  return value;',
    '}',
    '',
    "const runId = requiredGuardEnv('TRACEFLOW_RUN_ID');",
    "const runToken = requiredGuardEnv('TRACEFLOW_RUN_TOKEN');",
    "const workerBaseUrl = requiredGuardEnv('TRACEFLOW_WORKER_BASE_URL');",
    // Single source of truth: these are baked in from the runner's MAX_* consts so the
    // guard and the reported limits can never drift apart.
    'const maxToolResultChars = ' + MAX_TOOL_RESULT_CONTEXT_CHARS + ';',
    'const maxMessageChars = ' + MAX_MESSAGE_CONTEXT_CHARS + ';',
    'const maxProviderPayloadChars = ' + MAX_PROVIDER_PAYLOAD_CHARS + ';',
    '',
    'function textFromContent(content) {',
    "  if (typeof content === 'string') return content;",
    '  if (!Array.isArray(content)) return JSON.stringify(content ?? null);',
    '  return content',
    '    .map((part) => {',
    "      if (!part || typeof part !== 'object') return '';",
    "      if (part.type === 'text' && typeof part.text === 'string') return part.text;",
    "      if (part.type === 'thinking' && typeof part.thinking === 'string') return part.thinking;",
    '      return JSON.stringify(part);',
    '    })',
    '    .filter(Boolean)',
    "    .join('\\n\\n');",
    '}',
    '',
    'function hasToolCall(content) {',
    '  return Array.isArray(content) && content.some((part) => {',
    "    const type = part && typeof part === 'object' ? part.type : undefined;",
    "    return type === 'toolCall' || type === 'tool_call' || type === 'toolUse' || type === 'tool_use';",
    '  });',
    '}',
    '',
    '// The agent reads this verbatim. Tell it plainly what happened and what to do next,',
    '// so it self-corrects with a tighter query instead of paging the whole dataset into context.',
    'function rejectionText(kind, size, maxChars) {',
    '  return [',
    "    '[Trace Flow context guard] This ' + kind + ' was too large for the model context: ' + size + ' characters (limit ' + maxChars + ').',",
    "    'It was rejected, not truncated, so no partial or misleading data reached the model.',",
    "    'Retry with a more focused query: add filters, shorten the time window, lower the limit, or aggregate in Python (use the typed client at /workspace/traceflow_client.py and the *_raw summary methods).',",
    "    'Never print or return full DataFrames or raw rows; compute summaries in code and return only the result.'",
    "  ].join('\\n');",
    '}',
    '',
    'async function emitGuardEvent(message, data) {',
    '  await fetch(new URL("/pi-runs/events", workerBaseUrl), {',
    "    method: 'POST',",
    "    headers: { authorization: 'Bearer ' + runToken, 'content-type': 'application/json' },",
    '    body: JSON.stringify({',
    '      runId,',
    '      events: [{',
    "        type: 'status',",
    '        message,',
    '        emittedAt: Date.now(),',
    "        data: { phase: 'context_guard', ...data },",
    '      }],',
    '    }),',
    '  }).catch(() => undefined);',
    '}',
    '',
    'export default function traceflowContextGuard(pi) {',
    '  // Reject (not truncate) an oversized tool result. isError feeds it back to the agent',
    '  // as a failed call so it retries with a tighter query.',
    "  pi.on('tool_result', async (event) => {",
    '    const size = textFromContent(event.content).length;',
    '    if (size <= maxToolResultChars) return;',
    "    await emitGuardEvent('Pi tool result rejected as too large for context', {",
    '      toolName: event.toolName,',
    '      size,',
    '      maxChars: maxToolResultChars,',
    "      reason: 'tool_result_context_limit',",
    '    });',
    '    return {',
    '      isError: true,',
    "      content: [{ type: 'text', text: rejectionText('tool result from ' + (event.toolName ?? 'unknown'), size, maxToolResultChars) }],",
    '      details: {',
    '        ...(event.details ?? {}),',
    "        traceFlowContextGuard: { rejected: true, size, maxChars: maxToolResultChars, reason: 'tool_result_context_limit' },",
    '      },',
    '    };',
    '  });',
    '',
    '  // A single conversation message over the cap fails the turn loudly. There is no per-message',
    '  // reject channel here, and silently dropping it would hide data from the model.',
    "  pi.on('context', async (event) => {",
    '    for (const message of event.messages) {',
    '      if (!message || typeof message !== "object" || hasToolCall(message.content)) continue;',
    '      const size = textFromContent(message.content).length;',
    '      if (size <= maxMessageChars) continue;',
    "      await emitGuardEvent('Pi context message rejected as too large', {",
    "        role: message.role, size, maxChars: maxMessageChars, reason: 'message_context_limit',",
    '      });',
    "      throw new Error(rejectionText('conversation message (role ' + (message.role ?? 'unknown') + ')', size, maxMessageChars));",
    '    }',
    '  });',
    '',
    '  // Final backstop: the whole outgoing provider payload. Reject loudly rather than send a',
    '  // request that blows the context window.',
    "  pi.on('before_provider_request', async (event) => {",
    '    const size = JSON.stringify(event.payload ?? null).length;',
    '    if (size <= maxProviderPayloadChars) return;',
    "    await emitGuardEvent('Pi provider payload rejected as too large', {",
    "      size, maxChars: maxProviderPayloadChars, reason: 'provider_payload_context_limit',",
    '    });',
    "    throw new Error(rejectionText('provider request payload', size, maxProviderPayloadChars));",
    '  });',
    '',
    '  // Observe each provider HTTP response (fires after headers, before the stream body is',
    '  // consumed). A non-2xx or a response that never yields a body is the difference between',
    "  // 'the provider errored' and 'the agent is genuinely hanging' — record it so a stalled",
    '  // run is diagnosable instead of looking like silence.',
    "  pi.on('after_provider_response', async (event) => {",
    '    const response = event && event.response ? event.response : event;',
    "    const status = response && typeof response.status === 'number' ? response.status : undefined;",
    '    const hasBody = Boolean(response && (response.body || response.ok));',
    '    if (status !== undefined && status >= 200 && status < 300) return;',
    "    await emitGuardEvent('Pi provider response was not successful', {",
    "      reason: 'provider_response', status, hasBody,",
    '    });',
    '  });',
    '',
    '  // Best-effort checkpoint when the runtime is being torn down gracefully (e.g. a',
    '  // deploy rollout signals the container to exit). Snapshots /workspace + the Pi',
    '  // session to R2 so an auto-resume picks up mid-question instead of re-running it.',
    '  // A hard kill skips this; the resume then falls back to the last completed checkpoint.',
    "  pi.on('session_shutdown', async (event) => {",
    "    if (event && event.reason && event.reason !== 'quit') return;",
    '    const controller = new AbortController();',
    '    const timer = setTimeout(() => controller.abort(), 4000);',
    '    try {',
    "      await fetch(new URL('/pi-runs/checkpoint', workerBaseUrl), {",
    "        method: 'POST',",
    "        headers: { authorization: 'Bearer ' + runToken, 'content-type': 'application/json' },",
    '        body: JSON.stringify({ runId, sandboxId: process.env.TRACEFLOW_SANDBOX_ID }),',
    '        signal: controller.signal,',
    '      });',
    '    } catch (error) {',
    "      console.error('session_shutdown checkpoint failed', error);",
    '    } finally {',
    '      clearTimeout(timer);',
    '    }',
    '  });',
    '}',
    '',
  ].join('\n');
}`;
