import type { StartPiRunRequest } from './request';

const RUNNER_PATH = '/workspace/traceflow-pi-runner.mjs';
const REQUEST_PATH = (runId: string) => `/workspace/runs/${runId}/request.json`;
const CONTROL_PATH = (runId: string) => `/workspace/runs/${runId}/controls.jsonl`;

export function getPiRunnerPaths(runId: string) {
  return {
    runnerPath: RUNNER_PATH,
    requestPath: REQUEST_PATH(runId),
    controlPath: CONTROL_PATH(runId),
    runDir: `/workspace/runs/${runId}`,
  };
}

export function buildPiRunRequest(request: StartPiRunRequest) {
  return JSON.stringify(
    {
      runId: request.runId,
      prompt: request.prompt,
      pageContextReferences: request.pageContextReferences,
      maxRuntimeMs: request.maxRuntimeMs,
      model: request.model,
      toolDefinitions: request.toolDefinitions,
    },
    null,
    2,
  );
}

export function buildPiWorkspaceManifest() {
  return [
    '# Trace Flow Analyst Pi Runner',
    '',
    'This workspace is generated by Trace Flow for one sandboxed Analyst run.',
    '',
    'Trust boundary:',
    '- The workspace itself is intentionally trusted for Pi startup.',
    '- Ambient Pi discovery is disabled for skills, prompt templates, themes, context files, and project-local extensions.',
    '- The only loaded extension is the generated Trace Flow context guard for truncating oversized tool results and provider context.',
    '- Trace Flow data access must go through the traceflow_data tool.',
    '- traceflow_data writes raw approved data to /workspace/runs/<runId>/data and returns artifact paths, not inline datasets.',
    '- A sandbox-local Trace Flow Data API serves live OpenAPI at http://127.0.0.1:<port>/openapi.json for code-driven access.',
    '- Convex verifies the run token, creator, org, disabled-user state, and current permissions on every data call.',
    '- The sandbox does not receive Tinybird admin tokens, Convex admin credentials, OpenRouter keys, or user session tokens.',
    '',
    'Expected inputs:',
    '- /workspace/runs/<runId>/request.json',
    '- /workspace/runs/<runId>/controls.jsonl',
    '- /workspace/runs/<runId>/traceflow-context-guard.ts',
    '- /workspace/.pi/agent/models.json',
    '',
  ].join('\n');
}

export function buildPiModelsJson(model: string, aiProxyBaseUrl: string) {
  const cost = piModelCost(model);
  return JSON.stringify(
    {
      providers: {
        'traceflow-openrouter': {
          name: 'Trace Flow OpenRouter Proxy',
          baseUrl: aiProxyBaseUrl,
          api: 'openai-completions',
          authHeader: true,
          headers: {
            'HTTP-Referer': 'https://traceflow.dev',
            'X-Title': 'Trace Flow Analyst Pi',
          },
          models: [
            {
              id: model,
              name: model,
              reasoning: false,
              input: ['text'],
              contextWindow: 128000,
              maxTokens: 4096,
              cost,
              compat: {
                cacheControlFormat: 'anthropic',
              },
            },
          ],
        },
      },
    },
    null,
    2,
  );
}

function piModelCost(model: string) {
  if (model === 'z-ai/glm-5.2') {
    return { input: 0.95, output: 3, cacheRead: 0.18, cacheWrite: 0 };
  }
  return { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 };
}

export function buildPiRunnerScript() {
  return String.raw`import fs from 'node:fs/promises';
import http from 'node:http';
import path from 'node:path';

const runId = requiredEnv('TRACEFLOW_RUN_ID');
const runToken = requiredEnv('TRACEFLOW_RUN_TOKEN');
const sandboxId = requiredEnv('TRACEFLOW_SANDBOX_ID');
const workerBaseUrl = requiredEnv('TRACEFLOW_WORKER_BASE_URL');
const requestPath = requiredEnv('TRACEFLOW_REQUEST_PATH');
const controlPath = requiredEnv('TRACEFLOW_CONTROL_PATH');
const agentDir = process.env.PI_CODING_AGENT_DIR ?? '/workspace/.pi/agent';
const runDir = path.join('/workspace/runs', runId);
const dataDir = path.join(runDir, 'data');
const contextArtifactDir = path.join(runDir, 'context-artifacts');
const dataApiDescriptorPath = path.join(runDir, 'traceflow-data-api.json');
const contextGuardExtensionPath = path.join(runDir, 'traceflow-context-guard.ts');
const request = JSON.parse(await fs.readFile(requestPath, 'utf8'));
let resultText = '';
let completed = false;
let timedOut = false;
let session;
let dataApiServer;
let dataApiBaseUrl = '';
let controlOffset = 0;
const eventBuffer = [];
let flushQueue = Promise.resolve();
let timeoutTimer;
let controlTimer;
let flushTimer;
let idleTimer;
let heartbeatTimer;
let lastActivityAt = Date.now();
let piEventCount = 0;
let latestPhase = 'starting';
let latestToolName;
let latestUsageSignature = '';
let dataArtifactSeq = 0;
let latestToolResultText = '';
let latestToolResultName = '';
const IDLE_COMPLETION_MS = Math.min(60000, Math.max(20000, Math.round(request.maxRuntimeMs / 12)));
const MIN_IDLE_COMPLETION_TEXT_CHARS = 80;
const HEARTBEAT_MS = 10000;
const PROVIDER_REQUEST_TIMEOUT_MS = Math.min(request.maxRuntimeMs, 2 * 60 * 1000);
const PROVIDER_IDLE_TIMEOUT_MS = 30000;
const MAX_TOOL_RESULT_CONTEXT_CHARS = 12000;
const MAX_MESSAGE_CONTEXT_CHARS = 24000;
const MAX_PROVIDER_PAYLOAD_CHARS = 180000;

function requiredEnv(name) {
  const value = process.env[name];
  if (!value) throw new Error(name + ' is required');
  return value;
}

function safeStringify(value, maxChars = 6000) {
  try {
    const text = JSON.stringify(value);
    return text.length <= maxChars ? text : text.slice(0, maxChars) + '\n...[truncated]';
  } catch (error) {
    return error instanceof Error ? error.message : String(error);
  }
}

function truncateText(value, maxChars = 6000) {
  const text = typeof value === 'string' ? value : '';
  return text.length <= maxChars ? text : text.slice(0, maxChars) + '\n...[truncated]';
}

function buildTraceflowContextGuardExtension() {
  return [
    "import fs from 'node:fs/promises';",
    "import path from 'node:path';",
    '',
    "const runId = process.env.TRACEFLOW_RUN_ID ?? 'unknown-run';",
    "const runToken = process.env.TRACEFLOW_RUN_TOKEN ?? '';",
    "const workerBaseUrl = process.env.TRACEFLOW_WORKER_BASE_URL ?? '';",
    "const artifactDir = process.env.TRACEFLOW_CONTEXT_ARTIFACT_DIR ?? '/workspace/runs/' + runId + '/context-artifacts';",
    'const maxToolResultChars = Number(process.env.TRACEFLOW_MAX_TOOL_RESULT_CONTEXT_CHARS ?? 12000);',
    'const maxMessageChars = Number(process.env.TRACEFLOW_MAX_MESSAGE_CONTEXT_CHARS ?? 24000);',
    'const maxProviderPayloadChars = Number(process.env.TRACEFLOW_MAX_PROVIDER_PAYLOAD_CHARS ?? 180000);',
    'let seq = 0;',
    '',
    'function textFromContent(content) {',
    "  if (typeof content === 'string') return content;",
    '  if (!Array.isArray(content)) return JSON.stringify(content ?? null);',
    '  return content',
    '    .map((part) => {',
    "      if (!part || typeof part !== 'object') return '';",
    "      if (part.type === 'text' && typeof part.text === 'string') return part.text;",
    "      if (part.type === 'thinking' && typeof part.thinking === 'string') return part.thinking;",
    '      return JSON.stringify(part);',
    '    })',
    '    .filter(Boolean)',
    "    .join('\\n\\n');",
    '}',
    '',
    'function byteLength(value) {',
    "  return Buffer.byteLength(value, 'utf8');",
    '}',
    '',
    'function hasToolCall(content) {',
    '  return Array.isArray(content) && content.some((part) => {',
    "    const type = part && typeof part === 'object' ? part.type : undefined;",
    "    return type === 'toolCall' || type === 'tool_call' || type === 'toolUse' || type === 'tool_use';",
    '  });',
    '}',
    '',
    'function sanitizeSegment(value) {',
    '  return String(value)',
    "    .replace(/[^A-Za-z0-9_-]+/g, '-')",
    "    .replace(/^-+|-+$/g, '')",
    '    .slice(0, 80) || "message";',
    '}',
    '',
    'async function writeArtifact(kind, value) {',
    '  await fs.mkdir(artifactDir, { recursive: true });',
    "  const artifactPath = path.join(artifactDir, String(seq++).padStart(4, '0') + '-' + sanitizeSegment(kind) + '.json');",
    "  const text = typeof value === 'string' ? value : JSON.stringify(value, null, 2);",
    '  await fs.writeFile(artifactPath, text);',
    '  return { artifactPath, chars: text.length, bytes: byteLength(text) };',
    '}',
    '',
    'async function emitGuardEvent(message, data) {',
    '  if (!workerBaseUrl || !runToken) return;',
    '  await fetch(new URL("/pi-runs/events", workerBaseUrl), {',
    "    method: 'POST',",
    "    headers: { authorization: 'Bearer ' + runToken, 'content-type': 'application/json' },",
    '    body: JSON.stringify({',
    '      runId,',
    '      events: [{',
    "        type: 'status',",
    '        message,',
    '        emittedAt: Date.now(),',
    "        data: { phase: 'context_guard', ...data },",
    '      }],',
    '    }),',
    '  }).catch(() => undefined);',
    '}',
    '',
    'function replacementText(kind, artifact) {',
    '  return [',
    "    '[Trace Flow context guard] Large ' + kind + ' omitted from the LLM context.',",
    "    'Saved artifact: ' + artifact.artifactPath,",
    "    'Size: ' + artifact.bytes + ' bytes.',",
    "    'Use bash/Python/read to inspect the artifact and compute summaries locally. Do not paste raw rows into the conversation.'",
    "  ].join('\\n');",
    '}',
    '',
    'async function compactContent(kind, content, maxChars) {',
    '  const text = textFromContent(content);',
    '  if (text.length <= maxChars) return null;',
    '  const artifact = await writeArtifact(kind, content);',
    "  return { artifact, content: [{ type: 'text', text: replacementText(kind, artifact) }] };",
    '}',
    '',
    'function compactProviderPayload(payload) {',
    '  if (!payload || typeof payload !== "object") return payload;',
    '  const next = structuredClone(payload);',
    '  const messages = Array.isArray(next.messages) ? next.messages : Array.isArray(next.input) ? next.input : null;',
    '  if (!messages) return next;',
    '  for (const message of messages) {',
    '    if (!message || typeof message !== "object" || hasToolCall(message.content)) continue;',
    '    const text = textFromContent(message.content);',
    '    if (text.length > maxMessageChars) {',
    "      message.content = '[Trace Flow context guard] Oversized message removed before provider request. Inspect saved artifacts or rerun analysis code for details.';",
    '    }',
    '  }',
    '  return next;',
    '}',
    '',
    'export default function traceflowContextGuard(pi) {',
    "  pi.on('tool_result', async (event) => {",
    "    const label = 'tool-result-' + (event.toolName ?? 'unknown');",
    '    const compacted = await compactContent(label, event.content, maxToolResultChars);',
    '    if (!compacted) return;',
    "    await emitGuardEvent('Large Pi tool result saved outside LLM context', {",
    '      toolName: event.toolName,',
    '      artifactPath: compacted.artifact.artifactPath,',
    '      bytes: compacted.artifact.bytes,',
    '      maxChars: maxToolResultChars,',
    '    });',
    '    return {',
    '      content: compacted.content,',
    '      details: {',
    '        ...(event.details ?? {}),',
    '        traceFlowContextGuard: {',
    '          omitted: true,',
    '          artifactPath: compacted.artifact.artifactPath,',
    '          bytes: compacted.artifact.bytes,',
    '          reason: "tool_result_context_limit",',
    '        },',
    '      },',
    '    };',
    '  });',
    '',
    "  pi.on('context', async (event) => {",
    '    const messages = [];',
    '    let compactedCount = 0;',
    '    for (const message of event.messages) {',
    '      if (!message || typeof message !== "object" || hasToolCall(message.content)) {',
    '        messages.push(message);',
    '        continue;',
    '      }',
    '      const compacted = await compactContent("message-" + (message.role ?? "unknown"), message.content, maxMessageChars);',
    '      if (!compacted) {',
    '        messages.push(message);',
    '        continue;',
    '      }',
    '      compactedCount += 1;',
    '      messages.push({ ...message, content: compacted.content });',
    '    }',
    '    if (compactedCount > 0) {',
    "      await emitGuardEvent('Oversized Pi context messages saved outside LLM context', { compactedCount, maxChars: maxMessageChars });",
    '    }',
    '    return { messages };',
    '  });',
    '',
    "  pi.on('before_provider_request', async (event) => {",
    '    const text = JSON.stringify(event.payload ?? null);',
    '    if (text.length <= maxProviderPayloadChars) return;',
    '    const artifact = await writeArtifact("provider-payload", event.payload);',
    "    await emitGuardEvent('Oversized Pi provider payload compacted before send', {",
    '      artifactPath: artifact.artifactPath,',
    '      bytes: artifact.bytes,',
    '      maxChars: maxProviderPayloadChars,',
    '    });',
    '    const compacted = compactProviderPayload(event.payload);',
    '    const compactedText = JSON.stringify(compacted ?? null);',
    '    if (compactedText.length > maxProviderPayloadChars) {',
    "      throw new Error('Trace Flow context guard blocked an oversized provider payload after compaction: ' + compactedText.length + ' chars');",
    '    }',
    '    return compacted;',
    '  });',
    '}',
    '',
  ].join('\n');
}

function sanitizeArtifactSegment(value) {
  return (
    String(value)
      .replace(/[^A-Za-z0-9_-]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 80) || 'tool'
  );
}

async function writeTraceflowDataArtifact(toolName, args, result) {
  await fs.mkdir(dataDir, { recursive: true });
  const seq = String(dataArtifactSeq).padStart(4, '0');
  dataArtifactSeq += 1;
  const artifactPath = path.join(dataDir, seq + '-' + sanitizeArtifactSegment(toolName) + '.json');
  const payload = {
    toolName,
    arguments: args ?? {},
    fetchedAt: new Date().toISOString(),
    result,
  };
  const text = JSON.stringify(payload, null, 2);
  await fs.writeFile(artifactPath, text);
  return {
    toolName,
    artifactPath,
    chars: text.length,
    instructions:
      'Read this JSON file with the read tool or load it from Python/pandas. Raw Trace Flow data is not returned inline in this tool response.',
  };
}

function safeEventData(event) {
  return {
    event: safeStringify(event, 12000),
    eventType: typeof event?.type === 'string' ? event.type : 'session_event',
    assistantEventType:
      typeof event?.assistantMessageEvent?.type === 'string'
        ? event.assistantMessageEvent.type
        : undefined,
    toolCallId: typeof event?.toolCallId === 'string' ? event.toolCallId : undefined,
    toolName: typeof event?.toolName === 'string' ? event.toolName : undefined,
  };
}

function describeSessionEvent(event) {
  const eventType = typeof event?.type === 'string' ? event.type : 'session_event';
  const assistant = event?.assistantMessageEvent;
  const assistantEventType = typeof assistant?.type === 'string' ? assistant.type : undefined;
  const data = safeEventData(event);

  latestPhase = eventType;
  if (typeof event?.toolName === 'string') latestToolName = event.toolName;

  if (eventType === 'message_update' && assistantEventType?.startsWith('thinking_')) {
    return null;
  }

  if (eventType === 'message_update' && assistantEventType?.endsWith('_delta')) {
    const delta = typeof assistant.delta === 'string' ? assistant.delta : '';
    return delta ? {
      type: 'stdout',
      message: delta,
      data,
    } : null;
  }

  if (eventType === 'message_update' && assistantEventType) {
    return {
      type: 'message',
      message: assistantEventType.replaceAll('_', ' '),
      data,
    };
  }

  if (eventType === 'tool_execution_start') {
    return {
      type: 'message',
      message: 'tool started',
      data,
    };
  }

  if (eventType === 'tool_execution_update') {
    return {
      type: 'message',
      message: 'tool updated',
      data,
    };
  }

  if (eventType === 'tool_execution_end') {
    return {
      type: event?.isError ? 'error' : 'message',
      message: event?.isError ? 'tool failed' : 'tool completed',
      data,
    };
  }

  return {
    type: 'message',
    message: eventType.replaceAll('_', ' '),
    data,
  };
}

function appendResultText(text) {
  const next = typeof text === 'string' ? text : '';
  if (!next) return;
  resultText += next;
}

function messageContentText(message, includeThinking = false) {
  if (!message || typeof message !== 'object' || !Array.isArray(message.content)) return '';
  return message.content
    .map((part) => {
      if (!part || typeof part !== 'object') return '';
      if (part.type === 'text' && typeof part.text === 'string') return part.text;
      if (includeThinking && part.type === 'thinking' && typeof part.thinking === 'string') {
        return part.thinking;
      }
      return '';
    })
    .filter(Boolean)
    .join('\n\n');
}

function resultTextFromEvent(event) {
  if (event?.type !== 'turn_end') return '';
  return messageContentText(event.message);
}

function completedToolResultTextFromEvent(event) {
  if (event?.type !== 'tool_execution_end' || event?.isError) return '';
  return messageContentText(event.result);
}

function normalizeTraceflowArguments(value) {
  if (value === undefined || value === null) return {};
  if (typeof value === 'string') {
    const trimmed = value.trim();
    if (!trimmed) return {};
    const parsed = JSON.parse(trimmed);
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
      throw new Error('Trace Flow data arguments must be a JSON object');
    }
    return parsed;
  }
  if (typeof value === 'object' && !Array.isArray(value)) return value;
  throw new Error('Trace Flow data arguments must be an object');
}

function readToolDefinitions() {
  return Array.isArray(request.toolDefinitions)
    ? request.toolDefinitions.filter((definition) => definition && typeof definition === 'object')
    : [];
}

function readToolName(definition) {
  return typeof definition?.name === 'string' ? definition.name : undefined;
}

function readToolInputSchema(definition) {
  const schema = definition?.inputSchema;
  if (!schema || typeof schema !== 'object' || Array.isArray(schema)) {
    return { type: 'object', additionalProperties: true };
  }
  return schema;
}

function findToolDefinition(toolName) {
  return readToolDefinitions().find((definition) => readToolName(definition) === toolName);
}

function buildTraceflowOpenApiDocument() {
  const paths = {
    '/health': {
      get: {
        operationId: 'health',
        summary: 'Check the sandbox-local Trace Flow Data API.',
        responses: {
          '200': {
            description: 'API status.',
            content: { 'application/json': { schema: { type: 'object' } } },
          },
        },
      },
    },
    '/tools': {
      get: {
        operationId: 'list_traceflow_tools',
        summary: 'List approved Trace Flow tools for this run.',
        responses: {
          '200': {
            description: 'Approved tool definitions.',
            content: { 'application/json': { schema: { type: 'object' } } },
          },
        },
      },
    },
    '/tools/{toolName}': {
      post: {
        operationId: 'call_traceflow_tool',
        summary: 'Call an approved Trace Flow tool by name with raw JSON arguments.',
        description:
          'Returns the decoded JSON result directly. Use limit and cursor arguments when the tool schema exposes them.',
        parameters: [
          {
            name: 'toolName',
            in: 'path',
            required: true,
            schema: { type: 'string' },
          },
        ],
        requestBody: {
          required: false,
          content: {
            'application/json': {
              schema: { type: 'object', additionalProperties: true },
            },
          },
        },
        responses: {
          '200': {
            description: 'Decoded Trace Flow tool result.',
            content: { 'application/json': { schema: {} } },
          },
        },
      },
    },
  };

  for (const definition of readToolDefinitions()) {
    const name = readToolName(definition);
    if (!name) continue;
    paths['/tools/' + name] = {
      post: {
        operationId: name,
        summary: definition.description ?? 'Call ' + name,
        description:
          (definition.description ?? 'Call ' + name) +
          ' The request body is the tool JSON arguments. The response is the decoded JSON result. If the schema has limit/cursor fields, page through results until the result has no next cursor.',
        requestBody: {
          required: false,
          content: {
            'application/json': {
              schema: readToolInputSchema(definition),
            },
          },
        },
        responses: {
          '200': {
            description: 'Decoded Trace Flow tool result.',
            content: { 'application/json': { schema: {} } },
          },
        },
      },
    };
  }

  return {
    openapi: '3.1.0',
    info: {
      title: 'Trace Flow Sandbox Data API',
      version: '1.0.0',
      description:
        'Sandbox-local unauthenticated API for this Pi run. The server owns the run capability token; Convex validates current permissions on every data call.',
    },
    servers: [{ url: dataApiBaseUrl }],
    paths,
  };
}

function unwrapTraceflowToolResult(result) {
  if (result?.isError) {
    const message = result.content?.map((part) => part?.text).filter(Boolean).join('\\n') || 'Trace Flow tool failed';
    throw new Error(message);
  }
  const textParts = Array.isArray(result?.content)
    ? result.content.filter((part) => part?.type === 'text' && typeof part.text === 'string')
    : [];
  if (textParts.length === 1) {
    const text = textParts[0].text;
    try {
      return JSON.parse(text);
    } catch {
      return { text };
    }
  }
  return result;
}

async function readRequestJson(req) {
  const chunks = [];
  let size = 0;
  for await (const chunk of req) {
    size += chunk.length;
    if (size > 2_000_000) throw new Error('Request body is too large');
    chunks.push(chunk);
  }
  const text = Buffer.concat(chunks).toString('utf8').trim();
  if (!text) return {};
  const parsed = JSON.parse(text);
  return normalizeTraceflowArguments(parsed);
}

function sendJson(res, status, value) {
  const text = JSON.stringify(value);
  res.writeHead(status, {
    'content-type': 'application/json; charset=utf-8',
    'cache-control': 'no-store',
  });
  res.end(text);
}

async function handleTraceflowDataApiRequest(req, res) {
  const url = new URL(req.url ?? '/', dataApiBaseUrl || 'http://127.0.0.1');
  if (req.method === 'GET' && url.pathname === '/health') {
    sendJson(res, 200, { ok: true, runId, openapiUrl: dataApiBaseUrl + '/openapi.json' });
    return;
  }
  if (req.method === 'GET' && url.pathname === '/openapi.json') {
    sendJson(res, 200, buildTraceflowOpenApiDocument());
    return;
  }
  if (req.method === 'GET' && url.pathname === '/tools') {
    sendJson(res, 200, {
      openapiUrl: dataApiBaseUrl + '/openapi.json',
      tools: readToolDefinitions(),
    });
    return;
  }
  if (req.method === 'POST' && url.pathname.startsWith('/tools/')) {
    const toolName = decodeURIComponent(url.pathname.slice('/tools/'.length));
    if (!findToolDefinition(toolName)) {
      sendJson(res, 404, { error: 'Unknown Trace Flow tool: ' + toolName });
      return;
    }
    const args = await readRequestJson(req);
    const rawResult = await fetchTraceflowToolResult(toolName, args);
    sendJson(res, 200, unwrapTraceflowToolResult(rawResult));
    return;
  }
  sendJson(res, 404, { error: 'Not found' });
}

async function startTraceflowDataApi() {
  const server = http.createServer((req, res) => {
    void handleTraceflowDataApiRequest(req, res).catch((error) => {
      const message = error instanceof Error ? error.message : String(error);
      sendJson(res, 500, { error: message });
    });
  });

  await new Promise((resolve, reject) => {
    server.once('error', reject);
    server.listen(0, '127.0.0.1', () => {
      server.off('error', reject);
      resolve();
    });
  });

  const address = server.address();
  const port = typeof address === 'object' && address ? address.port : undefined;
  if (!port) {
    server.close();
    throw new Error('Trace Flow Data API did not bind to a local port');
  }
  dataApiServer = server;
  dataApiBaseUrl = 'http://127.0.0.1:' + port;
  await fs.writeFile(
    dataApiDescriptorPath,
    JSON.stringify(
      {
        baseUrl: dataApiBaseUrl,
        openapiUrl: dataApiBaseUrl + '/openapi.json',
        toolsUrl: dataApiBaseUrl + '/tools',
      },
      null,
      2,
    ),
  );
  return { baseUrl: dataApiBaseUrl, openapiUrl: dataApiBaseUrl + '/openapi.json' };
}

async function stopTraceflowDataApi() {
  if (!dataApiServer) return;
  const server = dataApiServer;
  dataApiServer = undefined;
  await new Promise((resolve) => server.close(resolve));
}

async function post(pathname, body) {
  const response = await fetch(new URL(pathname, workerBaseUrl), {
    method: 'POST',
    headers: {
      authorization: 'Bearer ' + runToken,
      'content-type': 'application/json',
    },
    body: JSON.stringify(body),
  });
  const json = await response.json().catch(() => null);
  if (!response.ok) {
    throw new Error(json?.error ?? 'Worker returned ' + response.status);
  }
  return json;
}

async function emit(event, options = {}) {
  if (options.markActivity !== false) lastActivityAt = Date.now();
  const next = { emittedAt: Date.now(), ...event };
  eventBuffer.push(next);
  console.log(JSON.stringify({ traceflow: next }));
  if (event.type !== 'stdout' || eventBuffer.length >= 8) await flushEvents();
}

function clearRunTimers() {
  clearTimeout(timeoutTimer);
  clearInterval(controlTimer);
  clearInterval(flushTimer);
  clearInterval(idleTimer);
  clearInterval(heartbeatTimer);
}

async function flushEvents() {
  flushQueue = flushQueue.then(flushEventsOnce, flushEventsOnce);
  return flushQueue;
}

async function flushEventsOnce() {
  if (eventBuffer.length === 0) return;
  const events = eventBuffer.splice(0, eventBuffer.length);
  await post('/pi-runs/events', { runId, events }).catch((error) => {
    console.error('failed to flush events', error);
    eventBuffer.unshift(...events.slice(-20));
  });
}

async function complete(status, payload = {}) {
  if (completed) return;
  completed = true;
  await flushEvents();
  await post('/pi-runs/complete', { runId, sandboxId, status, ...payload });
}

async function fetchTraceflowToolResult(toolName, args) {
  await flushEvents();
  const response = await post('/traceflow-data/tool', {
    runId,
    toolName,
    arguments: args ?? {},
  });
  return response.result;
}

async function callTraceflowTool(toolName, args) {
  const result = await fetchTraceflowToolResult(toolName, args);
  const artifact = await writeTraceflowDataArtifact(toolName, args ?? {}, result);
  await emit({
    type: 'status',
    message: 'Trace Flow data artifact written',
    data: {
      phase: 'data_artifact_written',
      toolName,
      artifactPath: artifact.artifactPath,
      chars: artifact.chars,
    },
  });
  return artifact;
}

function readSessionStats() {
  if (!session || typeof session.getSessionStats !== 'function') return undefined;
  try {
    const stats = session.getSessionStats();
    return {
      tokens: stats.tokens,
      cost: stats.cost,
      messages: {
        user: stats.userMessages,
        assistant: stats.assistantMessages,
        toolCalls: stats.toolCalls,
        toolResults: stats.toolResults,
        total: stats.totalMessages,
      },
      contextUsage: stats.contextUsage,
    };
  } catch {
    return undefined;
  }
}

async function emitUsage(reason) {
  const usage = readSessionStats();
  if (!usage) return;
  const signature = safeStringify(usage, 1000);
  if (signature === latestUsageSignature && reason !== 'final') return;
  latestUsageSignature = signature;
  await emit(
    {
      type: 'usage',
      message: 'Pi usage updated',
      data: { reason, usage },
    },
    { markActivity: false },
  );
}

async function emitHeartbeat() {
  const idleMs = Date.now() - lastActivityAt;
  await emit(
    {
      type: 'status',
      message: 'Pi runner heartbeat',
      data: {
        phase: latestPhase,
        latestToolName,
        idleMs,
        piEventCount,
        resultTextChars: resultText.length,
        isStreaming: Boolean(session?.isStreaming),
      },
    },
    { markActivity: false },
  );
  await emitUsage('heartbeat');
}

function createTraceflowDataTool(defineTool, Type) {
  return defineTool({
    name: 'traceflow_data',
    label: 'Trace Flow Data',
    description: 'Materialize approved Trace Flow data as a JSON artifact on disk and return its path plus metadata. Use this for traces, usage, costs, and agent analytics data.',
    promptSnippet: 'traceflow_data: materialize approved Trace Flow data artifacts by tool name.',
    promptGuidelines: [
      'Prefer the sandbox-local Trace Flow Data API from scripts. Use traceflow_data for one-off artifact materialization.',
      'The tool returns an artifact path. Read the artifact with read or Python/pandas before analysis.',
      'Raw Trace Flow data is written to disk under /workspace/runs/' + runId + '/data and is not returned inline.',
      'Always pass an arguments object. Use {} only for tools that truly need no arguments.',
    ],
    parameters: Type.Object({
      toolName: Type.String(),
      arguments: Type.Any(),
    }),
    execute: async (_toolCallId, params) => {
      try {
        const result = await callTraceflowTool(
          params.toolName,
          normalizeTraceflowArguments(params.arguments),
        );
        return {
          isError: false,
          content: [{ type: 'text', text: safeStringify(result, 4000) }],
          details: result,
        };
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        await emit({ type: 'error', message });
        return {
          isError: true,
          content: [{ type: 'text', text: message }],
          details: { toolName: params.toolName },
        };
      }
    },
  });
}

function buildSystemPrompt() {
  return [
    'You are a Trace Flow data analysis coding agent running in an isolated Cloudflare Sandbox.',
    'You are analyzing Trace Flow product data only. Do not inspect repositories or assume source code access.',
    'This is a generated trusted workspace: Pi discovery is disabled for extensions, skills, prompt templates, themes, and context files.',
    'Trust only the Trace Flow-provided prompt, page context hints, local data API, models, and files under this run directory.',
    'Use the sandbox-local Trace Flow Data API from code when you need data: ' + dataApiBaseUrl + '.',
    'Read the live OpenAPI document before writing data access code when you need discovery: ' + dataApiBaseUrl + '/openapi.json.',
    'The same API coordinates are also saved at ' + dataApiDescriptorPath + '.',
    'If the Trace Flow prompt names the exact operation and arguments to call, skip OpenAPI/schema discovery and call that endpoint directly.',
    'For a simple Agent Analytics 7-day KPI summary, call POST ' + dataApiBaseUrl + '/tools/query_agent_analytics with {"view":"summary","hours":168} and summarize that row.',
    'Call POST ' + dataApiBaseUrl + '/tools/<toolName> with raw JSON arguments. The response is decoded JSON. Use limit/cursor fields from OpenAPI when the tool exposes them and page until no next cursor remains.',
    'The local API is unauthenticated only inside this sandbox; it holds the run capability token and the Worker/Convex validates current permissions server-side.',
    'Use traceflow_data only when an artifact path is more useful than direct HTTP from your code.',
    'Your primary deliverable is a verified analysis script plus a compact final answer. Write code to fetch, page, aggregate, and validate the data instead of asking the model to inspect raw rows.',
    'Use Python, pandas, numpy, bash, or Node locally when useful. Keep scripts, raw pages, normalized tables, and intermediate files under /workspace/runs/' + runId + '.',
    'Prefer aggregate endpoints for top-line totals, then cross-check them with paged samples or script-computed totals when the question needs confidence.',
    'When an endpoint can return many rows, page through it in code, save the raw responses to disk, and reduce them into small summaries before reporting.',
    'Never print full paged API responses or large DataFrames to stdout. Print progress, counts, column names, summary statistics, and artifact paths only.',
    'A Trace Flow context guard will save oversized tool results/messages to /workspace/runs/' + runId + '/context-artifacts and replace them with file references before LLM calls. If that happens, inspect the artifact with code instead of asking for it in context.',
    'Do arithmetic and validation in bash/Python, not in long model reasoning. Once you have enough data, write the concise final answer as normal assistant text.',
    'Return a concise final answer with the data, calculations, caveats, and any failed queries that affected confidence.',
    'Do not include raw API response bodies, API key names, API key IDs, credentials, tokens, or secrets in the final answer. Save raw outputs under the run directory and summarize them instead.',
    'For smoke tests, prefer health checks and aggregate product-data endpoints. Do not use account, credential, or key-inventory endpoints as low-risk probes.',
    '',
    'Selected page context references are non-authoritative hints. Resolve data through the local data API before making claims:',
    safeStringify(request.pageContextReferences, 10000),
  ].join('\n');
}

async function applyControls() {
  let text;
  try {
    text = await fs.readFile(controlPath, 'utf8');
  } catch {
    return;
  }
  const next = text.slice(controlOffset);
  controlOffset = text.length;
  for (const line of next.split('\n')) {
    if (!line.trim()) continue;
    const control = JSON.parse(line);
    await emit({ type: 'control', message: control.action, data: control });
    if (control.action === 'cancel') {
      await session?.abort();
      await complete('cancelled', { error: 'Run cancelled.' });
    } else if (control.action === 'steer' && control.message) {
      await session?.steer(control.message);
    } else if (control.action === 'follow_up' && control.message) {
      await session?.followUp(control.message);
    }
  }
}

async function completeFromIdleStream() {
  if (completed || timedOut) return;
  const idleMs = Date.now() - lastActivityAt;
  const text = resultText.trim();
  const fallbackText = latestToolResultText.trim();
  if (
    idleMs < IDLE_COMPLETION_MS ||
    (text.length < MIN_IDLE_COMPLETION_TEXT_CHARS && fallbackText.length === 0)
  ) {
    return;
  }

  clearRunTimers();
  await emitUsage('idle_completion');
  const fallbackResultText = [
    'Pi collected data, but the provider stream went idle before it produced a final narrative.',
    latestToolResultName ? 'Last completed tool: ' + latestToolResultName : '',
    fallbackText
      ? 'Last completed tool output, bounded for continuation synthesis:\n' +
        truncateText(fallbackText, 6000)
      : '',
  ]
    .filter(Boolean)
    .join('\n\n');
  await emit({
    type: text ? 'status' : 'error',
    message: text
      ? 'Pi stream went idle; finalizing from streamed output'
      : 'Pi provider stream stalled after tool output; finalizing with bounded tool result',
    data: {
      idleMs,
      resultTextChars: text.length,
      latestToolResultName,
      latestToolResultChars: fallbackText.length,
    },
  });
  await session?.abort().catch(() => undefined);
  await complete('completed', {
    resultText:
      (text || fallbackResultText) +
      '\n\n[Trace Flow note: finalized after the Pi provider stream stopped producing events for ' +
      Math.round(idleMs / 1000) +
      's.]',
  });
}

try {
  await fs.mkdir(path.dirname(controlPath), { recursive: true });
  await fs.mkdir(agentDir, { recursive: true });
  await fs.rm(path.join(agentDir, 'extensions'), { recursive: true, force: true });
  await fs.rm('/workspace/.pi/extensions', { recursive: true, force: true });
  await fs.mkdir(contextArtifactDir, { recursive: true });
  await fs.writeFile(contextGuardExtensionPath, buildTraceflowContextGuardExtension());
  await emit({
    type: 'status',
    message: 'Starting Pi session',
    data: {
      phase: 'starting',
      trustedWorkspace: '/workspace',
      agentDir,
      discoveryTrust:
        'Trace Flow generates this trusted workspace and disables ambient Pi discovery.',
    },
  });
  const dataApi = await startTraceflowDataApi();
  await emit({
    type: 'status',
    message: 'Trace Flow Data API ready',
    data: {
      phase: 'data_api_ready',
      baseUrl: dataApi.baseUrl,
      openapiUrl: dataApi.openapiUrl,
      descriptorPath: dataApiDescriptorPath,
    },
  });
  await emit({
    type: 'status',
    message: 'Trace Flow context guard ready',
    data: {
      phase: 'context_guard_ready',
      extensionPath: contextGuardExtensionPath,
      artifactDir: contextArtifactDir,
      maxToolResultChars: MAX_TOOL_RESULT_CONTEXT_CHARS,
      maxMessageChars: MAX_MESSAGE_CONTEXT_CHARS,
      maxProviderPayloadChars: MAX_PROVIDER_PAYLOAD_CHARS,
    },
  });
  await emit({
    type: 'status',
    message: 'Loading Pi runtime',
    data: { phase: 'loading_runtime' },
  });
  timeoutTimer = setTimeout(() => {
    timedOut = true;
    void emitUsage('timeout');
    void emit({ type: 'error', message: 'Run timed out' });
    void session?.abort();
    void complete('timed_out', {
      error: 'Run timed out.',
      resultText: resultText.trim() || undefined,
    });
  }, request.maxRuntimeMs);

  const [
    {
      AuthStorage,
      createAgentSession,
      DefaultResourceLoader,
      defineTool,
      ModelRegistry,
      SessionManager,
      SettingsManager,
    },
    { Type },
  ] = await Promise.all([
    import('@earendil-works/pi-coding-agent'),
    import('typebox'),
  ]);
  const traceflowDataTool = createTraceflowDataTool(defineTool, Type);
  await emit({ type: 'status', message: 'Pi runtime loaded' });

  const authStorage = AuthStorage.create(path.join(agentDir, 'auth.json'));
  authStorage.setRuntimeApiKey('traceflow-openrouter', runToken);
  const modelRegistry = ModelRegistry.create(authStorage, path.join(agentDir, 'models.json'));
  const model = modelRegistry.find('traceflow-openrouter', request.model);
  if (!model) throw new Error('Pi model not found: ' + request.model);

  const settingsManager = SettingsManager.inMemory(
    {
      defaultProjectTrust: 'always',
      quietStartup: true,
      enableAnalytics: false,
      enableInstallTelemetry: false,
      transport: 'sse',
      httpIdleTimeoutMs: PROVIDER_IDLE_TIMEOUT_MS,
      websocketConnectTimeoutMs: 30000,
      compaction: { enabled: true },
      retry: {
        enabled: true,
        maxRetries: 1,
        provider: {
          timeoutMs: PROVIDER_REQUEST_TIMEOUT_MS,
          maxRetries: 0,
          maxRetryDelayMs: 60000,
        },
      },
      packages: [],
      extensions: [contextGuardExtensionPath],
      skills: [],
      prompts: [],
      themes: [],
    },
    { projectTrusted: true },
  );
  const resourceLoader = new DefaultResourceLoader({
    cwd: '/workspace',
    agentDir,
    settingsManager,
    noExtensions: false,
    noSkills: true,
    noPromptTemplates: true,
    noThemes: true,
    noContextFiles: true,
    systemPromptOverride: buildSystemPrompt,
  });
  await resourceLoader.reload({ resolveProjectTrust: async () => true });
  await emit({
    type: 'status',
    message: 'Pi runtime configured',
    data: {
      phase: 'runtime_configured',
      discovery: {
        extensions: ['traceflow-context-guard'],
        skills: false,
        promptTemplates: false,
        themes: false,
        contextFiles: false,
      },
      projectTrusted: true,
      trustBoundary:
        'Only Trace Flow-provided prompt, page context, tools, models, and run files are trusted.',
      providerTimeoutMs: PROVIDER_REQUEST_TIMEOUT_MS,
      providerIdleTimeoutMs: PROVIDER_IDLE_TIMEOUT_MS,
    },
  });

  const created = await createAgentSession({
    cwd: '/workspace',
    agentDir,
    model,
    thinkingLevel: 'off',
    authStorage,
    modelRegistry,
    tools: ['read', 'write', 'bash', 'grep', 'find', 'ls', 'traceflow_data'],
    customTools: [traceflowDataTool],
    resourceLoader,
    sessionManager: SessionManager.inMemory('/workspace'),
    settingsManager,
  });
  session = created.session;
  session.subscribe((event) => {
    piEventCount += 1;
    const displayEvent = describeSessionEvent(event);
    if (displayEvent) void emit(displayEvent);
    if (event.type === 'message_update' && event.assistantMessageEvent?.type === 'text_delta') {
      appendResultText(event.assistantMessageEvent.delta);
    }
    const turnText = resultTextFromEvent(event);
    if (turnText && !resultText.includes(turnText)) {
      appendResultText((resultText.trim() ? '\n\n' : '') + turnText);
    }
    const toolResultText = completedToolResultTextFromEvent(event);
    if (toolResultText) {
      latestToolResultText = toolResultText;
      latestToolResultName = typeof event.toolName === 'string' ? event.toolName : '';
    }
    if (
      event.type === 'message_end' ||
      event.type === 'turn_end' ||
      event.type === 'agent_end' ||
      event.type === 'tool_execution_end'
    ) {
      void emitUsage('pi_event');
    }
  });

  controlTimer = setInterval(() => void applyControls(), 2000);
  flushTimer = setInterval(() => void flushEvents(), 5000);
  idleTimer = setInterval(() => void completeFromIdleStream(), 5000);
  heartbeatTimer = setInterval(() => void emitHeartbeat(), HEARTBEAT_MS);

  try {
    await emit({
      type: 'status',
      message: 'Running Pi analysis',
      data: { phase: 'running' },
    });
    await emitHeartbeat();
    await session.prompt(request.prompt);
    clearRunTimers();
    await emitUsage('final');
    if (timedOut) {
      await complete('timed_out', {
        error: 'Run timed out.',
        resultText: resultText.trim() || undefined,
      });
    } else {
      await emit({ type: 'status', message: 'Pi analysis completed' });
      await complete('completed', {
        resultText: resultText.trim() || 'Pi completed without assistant text output.',
      });
    }
  } catch (error) {
    clearRunTimers();
    if (completed) {
      // Idle completion may abort the underlying SDK call after persisting a useful answer.
    } else {
      const message = error instanceof Error ? error.message : String(error);
      const status = timedOut ? 'timed_out' : completed ? 'cancelled' : 'failed';
      await emitUsage(status);
      await emit({ type: 'error', message });
      await complete(status, { error: message, resultText: resultText.trim() || undefined });
    }
  } finally {
    session?.dispose();
    await stopTraceflowDataApi();
  }
} catch (error) {
  clearRunTimers();
  const message = error instanceof Error ? error.message : String(error);
  await emitUsage('failed_startup');
  await emit({ type: 'error', message });
  await complete('failed', { error: message, resultText: resultText.trim() || undefined });
  await stopTraceflowDataApi();
}
`;
}
